version: 0.2
phases:
  pre_build:
    commands:
      - aws codeartifact login --tool npm --repository worldwideandweb-dependancies --domain worldwideandweb --domain-owner 460234074473
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      # copy the contents of /build to S3
      - aws s3 cp --recursive --acl public-read ./build s3://${DEPLOY_BUCKET}/ 
      - aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION} --paths ./index.html
artifacts:
  files:
    - '**/*'
  base-directory: build